# **You Wanna Live Where?**

## Objectives

* Exploratory Data Analysis on the countries, Austria, Belgium and Ireland, as part of the larger scope of Western Europe.

## Inputs

* The verified dataset - cost_of_living_verified.csv

* Libraries containing the tools to do EDA and render visualisations, pandas, numpy, matplotlib, seaborn.

## Outputs

* Visualisations 

* Evalutaions of the three countries in isolation against the "Affordibility Rule", to be then taken into the larger context of Western Europe.

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Capston Projects\\Hackathon\\Hackathon_Where_You_Wanna_Live\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Capston Projects\\Hackathon\\Hackathon_Where_You_Wanna_Live'

# Import Block

Libraries required to perfrom operations and visualisations

In [4]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
import seaborn as sns

In [ ]:
# Load the dataset into a dataframe
df_verified = pd.read_csv("Dataset/Verified/cost_of_living_verified.csv")

# Verify the dataframe
df_verified.head(5)

,country,cost_of_living_index,rent_index,cost_of_living_plus_rent_index,groceries_index,restaurant_price_index,local_purchasing_power_index,year,period,continent
0,Bermuda,135.8,108.2,123.5,143.4,147.5,101.3,2026,year,North America
1,Cayman Islands,115.6,76.1,97.9,124.0,101.5,149.6,2026,year,North America
2,US Virgin Islands,111.3,46.8,82.5,127.4,94.8,89.8,2026,year,North America
3,Switzerland,110.7,51.5,84.3,109.7,111.3,170.6,2026,year,Europe
4,Solomon Islands,102.3,19.5,65.4,64.8,46.0,12.6,2026,year,Oceania

To reduce unecessary cell ouput, the three target countries for this notebook will be segragated into another dataframe.

In [14]:
# Storing the three countries into a variable to work with
my_countries = ["Austria", "Belgium", "Ireland"]

# Declaring the dataframes values
my_df = df_verified[df_verified["country"].isin(my_countries)].copy()

# Verify country selection
my_df.head(10).sort_index(ascending=True)

,country,cost_of_living_index,rent_index,cost_of_living_plus_rent_index,groceries_index,restaurant_price_index,local_purchasing_power_index,year,period,continent
18,Austria,71.3,25.1,50.7,72.6,71.5,120.0,2026,year,Europe
19,Ireland,70.6,43.8,58.7,68.8,76.6,114.4,2026,year,Europe
24,Belgium,68.6,23.8,48.6,66.4,80.7,124.2,2026,year,Europe
170,Austria,60.7,22.0,43.6,62.2,59.7,107.1,2025,year,Europe
172,Ireland,59.8,39.0,50.6,56.9,65.8,108.9,2025,year,Europe
181,Belgium,56.5,19.3,40.1,54.6,67.1,116.1,2025,year,Europe
312,Austria,66.8,23.7,46.4,64.8,59.0,84.4,2024,year,Europe
313,Ireland,66.5,47.3,57.4,58.9,65.9,82.0,2024,year,Europe
321,Belgium,63.0,21.4,43.3,56.1,67.8,90.7,2024,year,Europe
457,Ireland,70.5,44.4,58.0,55.8,71.9,82.6,2023,year,Europe

---

# Section 1

We'll start with Austria. First we'll take peak at Austria's cost of living index and the cost living index plus rent.

In [13]:
print(my_df.groupby("country")["cost_of_living_index"])

<pandas.core.groupby.generic.SeriesGroupBy object at 0x00000191D57FAD50>

---

NOTE

* You may add as many sections as you want, as long as it supports your project workflow.
* All notebook's cells should be run top-down (you can't create a dynamic wherein a given point you need to go back to a previous cell to execute some task, like go back to a previous cell and refresh a variable content)

---

# Push files to Repo

* In cases where you don't need to push files to Repo, you may replace this section with "Conclusions and Next Steps" and state your conclusions and next steps.

In [7]:
import os
try:
  # create your folder here
  # os.makedirs(name='')
except Exception as e:
  print(e)

IndentationError: expected an indented block after 'try' statement on line 2 (553063055.py, line 5)