# **You Wanna Live Where?**

## Objectives

* Perfrom ETL on the cost_of_living.csv

## Inputs

* The dataset - cost_of_living.csv

* Libraries containing the tools to do ETL and render visualisations, pandas, numpy, matplotlib, seaborn.

## Outputs

* Descriptive statistics of the the dataset 

* A cleaned .csv for EDA

---

# Change working directory

* We are assuming you will store the notebooks in a subfolder, therefore when running the notebook in the editor, you will need to change the working directory

We need to change the working directory from its current folder to its parent folder
* We access the current directory with os.getcwd()

In [1]:
import os
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Capston Projects\\Hackathon\\Hackathon_Where_You_Wanna_Live\\jupyter_notebooks'

We want to make the parent of the current directory the new current directory
* os.path.dirname() gets the parent directory
* os.chir() defines the new current directory

In [2]:
os.chdir(os.path.dirname(current_dir))
print("You set a new current directory")

You set a new current directory

Confirm the new current directory

In [3]:
current_dir = os.getcwd()
current_dir

'c:\\Users\\NateM\\Desktop\\CI_DA\\Capston Projects\\Hackathon\\Hackathon_Where_You_Wanna_Live'

# Import Block

Libraries required to perfrom operations and visualisations

In [4]:
import pandas as pd 
import numpy as np 
import matplotlib as plt
import seaborn as sns 

from HelperFuncs import InitialInspect

---

# Section 1- Extract

Loading the raw .csv into a pandas dataframe

In [7]:
# Load the dataset into a dataframe
df_raw = pd.read_csv("Dataset/cost_of_living.csv")

# Verify the dataframe
df_raw.head(5)

,country,cost_of_living_index,rent_index,cost_of_living_plus_rent_index,groceries_index,restaurant_price_index,local_purchasing_power_index,year,period,continent
0,Bermuda,135.8,108.2,123.5,143.4,147.5,101.3,2026,year,North America
1,Cayman Islands,115.6,76.1,97.9,124.0,101.5,149.6,2026,year,North America
2,US Virgin Islands,111.3,46.8,82.5,127.4,94.8,89.8,2026,year,North America
3,Switzerland,110.7,51.5,84.3,109.7,111.3,170.6,2026,year,Europe
4,Solomon Islands,102.3,19.5,65.4,64.8,46.0,12.6,2026,year,Oceania

In [6]:
InitialInspect(df_raw)

Initial shape: (Row x Col) (1223, 10)
==================================================
Columns data types:
 country                            object
cost_of_living_index              float64
rent_index                        float64
cost_of_living_plus_rent_index    float64
groceries_index                   float64
restaurant_price_index            float64
local_purchasing_power_index      float64
year                                int64
period                             object
continent                          object
dtype: object
==================================================
Missing value counts:
country: 0.
cost_of_living_index: 0.
rent_index: 0.
cost_of_living_plus_rent_index: 0.
groceries_index: 0.
restaurant_price_index: 0.
local_purchasing_power_index: 0.
year: 0.
period: 0.
continent: 0.
==================================================
Duplicate counts:
country: 1066 duplicates.
cost_of_living_index: 657 duplicates.
rent_index: 823 duplicates.
cost_of_living_plus_rent_index: 743 duplicates.
groceries_index: 682 duplicates.
restaurant_price_index: 640 duplicates.
local_purchasing_power_index: 496 duplicates.
year: 1214 duplicates.
period: 1222 duplicates.
continent: 1217 duplicates.
==================================================
The .describe summary:

,cost_of_living_index,rent_index,cost_of_living_plus_rent_index,groceries_index,restaurant_price_index,local_purchasing_power_index,year
count,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000,1223.000000
mean,48.689534,18.649714,34.567048,45.581030,42.212347,55.999182,2022.204415
std,20.221341,14.426711,16.755419,19.933582,23.394244,34.183070,2.555584
min,17.800000,2.000000,11.000000,14.900000,12.000000,1.400000,2018.000000
25%,33.900000,9.500000,22.550000,31.200000,25.000000,30.300000,2020.000000
50%,43.900000,13.900000,30.200000,40.500000,35.400000,46.100000,2022.000000
75%,58.850000,23.100000,42.600000,55.250000,53.800000,79.450000,2024.000000
max,146.000000,108.200000,123.800000,148.700000,159.200000,200.800000,2026.000000

==================================================
First 10 rows

,country,cost_of_living_index,rent_index,cost_of_living_plus_rent_index,groceries_index,restaurant_price_index,local_purchasing_power_index,year,period,continent
0,Bermuda,135.8,108.2,123.5,143.4,147.5,101.3,2026,year,North America
1,Cayman Islands,115.6,76.1,97.9,124.0,101.5,149.6,2026,year,North America
2,US Virgin Islands,111.3,46.8,82.5,127.4,94.8,89.8,2026,year,North America
3,Switzerland,110.7,51.5,84.3,109.7,111.3,170.6,2026,year,Europe
4,Solomon Islands,102.3,19.5,65.4,64.8,46.0,12.6,2026,year,Oceania
5,Bahamas,98.8,50.2,77.1,100.9,109.0,57.1,2026,year,North America
6,Iceland,97.2,49.5,75.9,104.5,104.9,113.7,2026,year,Europe
7,Jersey,88.7,52.4,72.5,79.0,102.3,103.4,2026,year,Europe
8,Singapore,87.7,73.1,81.2,77.3,55.5,105.5,2026,year,Asia
9,Norway,83.7,29.2,59.4,85.4,88.6,124.7,2026,year,Europe

==================================================

---